#[cfg(target_os = "windows")]
pub mod amsi;
pub mod archive;
pub mod benchmark;
pub mod encoding;
pub mod hash;
pub mod localization;
pub mod serde_helpers;
pub mod settings;
#[cfg(feature = "gui")]
pub mod tauri_commands;
pub mod update;
